# Generated by Django 4.2 on 2024-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
