# Generated by Django 4.2 on 2024-12-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_movie_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(related_name='movies', to='Core.producer'),
        ),
    ]
