# Generated by Django 4.2 on 2024-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_movie_producer_movie_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='studio',
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ManyToManyField(related_name='movies', to='Core.studio'),
        ),
    ]
